
### EP10: Listar todas as tags (Vai dar lista vazia [] no início)
GET http://localhost:8080/publicacoescientificas/api/tags
Accept: application/json

### EP12: Criar uma Tag nova
POST http://localhost:8080/publicacoescientificas/api/tags
Content-Type: application/json

{
  "name": "ProjetoX"
}

### EP12: Criar outra Tag
POST http://localhost:8080/publicacoescientificas/api/tags
Content-Type: application/json

{
  "name": "InteligenciaArtificial"
}

### EP11: Ver detalhes da tag 1 (A do ProjetoX)
GET http://localhost:8080/publicacoescientificas/api/tags/1
Accept: application/json

### EP13: Mudar o nome da tag 1 para "ProjetoFinal"
PUT http://localhost:8080/publicacoescientificas/api/tags/1
Content-Type: application/json

{
  "name": "ProjetoFinal"
}

### EP14: Apagar a tag 2 (InteligenciaArtificial)
DELETE http://localhost:8080/publicacoescientificas/api/tags/2



###EP20: Criar uma nova publicação científica
POST http://localhost:8080/publicacoescientificas/api/publications
Content-Type: application/json

{
  "titulo": "Deep Learning aplicado à análise de dados científicos",
  "autores": ["João A", "Maria C", "Joana B"],
  "area": "Ciência de Dados",
  "tipo": "Artigo Científico",
  "resumoCurto": "Artigo sobre métodos de redes neurais...",
  "username": "ColaboradorA",
  "visivel": false
}




###EP21: Listar todas as publicações
GET http://localhost:8080/publicacoescientificas/api/publications/
Accept: application/json


###EP22: Listar publicações por ID
GET http://localhost:8080/publicacoescientificas/api/publications/1
Accept: application/json


###EP23: Atualizar uma publicação (tornar visível)
PUT http://localhost:8080/publicacoescientificas/api/publications/1
Content-Type: application/json

{
  "titulo": "Deep Learning aplicado à análise de dados científicos (Versão Atualizada)",
  "autores": ["João A", "Maria C", "Joana BBBB"],
  "area": "Ciência de Dados",
  "tipo": "Artigo Científico",
  "resumoCurto": "Atualização com novos resultados...",
  "visivel": true
}


###EP24: Apagar uma publicação
DELETE http://localhost:8080/publicacoescientificas/api/publications/3


###EP25: Upload de ficheiro para uma publicação
POST http://localhost:8080/publicacoescientificas/api/publications/1/upload
Authorization: Bearer << insert token here >>
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="ProjetoX.pdf"
Content-Type: application/pdf

<conteúdo do ficheiro aqui>
--boundary--


###EP26: Download de ficheiro de uma publicação
GET http://localhost:8080/publicacoescientificas/api/publications/1/download
Authorization: Bearer << insert token here >>